### ISSUE TITLE
Raised issues in ESPHome issues

### ISSUE THREAD

**Issue by Samywamy10** [clydebarrow/esphome#122]
Hi,
Firstly, thanks so much for your work here. Absolutely having a blast setting up UI for a display I bought.

I've noticed there's a few issues being raised in this repo. I've raised two issues in the ESPhome issues tracker (given the 2024.8 release is now out) but would they be better here?
- https://github.com/esphome/issues/issues/6190
- https://github.com/esphome/issues/issues/6184

Thanks again :)

**Comment by clydebarrow** [comment]
Now that it's been released in ESPHome, that issue tracker is the right place. But, I don't regularly look at that, so it would be good to mention it in the [Discord channel ](https://discord.com/channels/429907082951524364/1270223320989831178) - no need to tag me, I do look at that channel regularly.
