### ISSUE TITLE
`label` options

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#26]
From https://docs.lvgl.io/8.3/widgets/core/label.html:
- ~Long modes options~
- Custom scrolling animations
- ~Symbols~

Implement Label as text input component (bi-directionally, eg display text from HA; although a Text Sensor can also do it, not sure if it's worth both).

**Comment by nagyrobi** [comment]
Also new line with `\n`, Would be good because it's rather easy to generate such strings from HA templates or within ESPHome lambdas.

**Comment by 4ib3r** [comment]
Hello, I created PR with improvements (recolor and long modes) from this issue :wink:

**Comment by nagyrobi** [comment]
~Yes, for recolor only we could use the same as `btnmatrix` control offers, `recolor: true`.~

I used to implement dots in a label showing the current (hidden) tab with recolor. The active tab's dot was colored black, the others were grey, and all I had to do is to update the string in the label, based on the active tab.

EDIT: Done

**Comment by nagyrobi** [comment]
Until recently it was possible to start with an empty string `text: ""`. Now this doesn't work, it reverts to default "Text" of lvgl.

Reason to start with empty string is to display sensor values which may not yet be ready at boot, for example.

**Comment by clydebarrow** [comment]
> Until recently it was possible to start with an empty string `text: ""`. Now this doesn't work

Fixed.

The animation stuff should be a separate issue to implement custom animations generally.
