### ISSUE TITLE
suggestion to rename 'obj' to 'widget'

### ISSUE THREAD

**Issue by nielsnl68** [clydebarrow/esphome#36]
In the LVGL component you already have named button's and labels etc widgets.

But everywhere else you address them as obj's, my suggestion is to name them globally "widgets"

**Comment by clydebarrow** [comment]
Obj is also used to refer to things that don't fall into the widget category, it can include pages, and the top_layer. There might be places where widget would be better, I'll have a look.

**Comment by clydebarrow** [comment]
Ok, done.
