### ISSUE TITLE
`binary_sensor` should reflect `checked` state + `publish_initial_state` config

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#42]
With `btn` and `btnmatrix`, `binary_sensor` only activates while clicking. If the button has `checkable: true` set, the state should remain TRUE while checked.

Also, `publish_initial_state` option of `binary_sensor` is not respected. It defaults to `true` (which is good) but can't be overridden from config to `false`. This is important for cases when one doesn't care about the looks, but rather wouldn't want to have automations depending on this to run at boot.

**Comment by clydebarrow** [comment]
The binary sensor reflects pressing, not checked. For checked state, use switch.

publish_initial_state issue is fixed.
