### ISSUE TITLE
VNC tweaks

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#50]
There seems to be a bug in the `host` which prevents re-connection after disconnection. Nothing is printed in the log, but client complains "Failed to receive data from socket." If I close the client, and try to connect back again.

---

My vnc client has clipboard synchronisation, and it looks like that the implemented VNC client supports it. See **Received cut buffer**:
```
[D][vnc:294]: Accepted x.x.x.x
[D][vnc:650]: Read RFB 003.003
 as version
[I][vnc:666]: Client requested authentication 1
[D][vnc:563]: Read 11 encoding types
[D][vnc:623]: Received cut buffer My vnc client has clipboard syncronization
[D][vnc:623]: Received cut buffer  and it looks like that the implemented VNC client supports it. 

[W][vnc:632]: Unknown command 97
[W][vnc:632]: Unknown command 99
```
However it's of little use here so I'd suggest to disbale it. Seems like certain copied texts are interpreted as commands which may lead to potential issues.

**Comment by clydebarrow** [comment]
Fixed, this is merged into the lvgl branch.
