### ISSUE TITLE
`obj` propagate down `state` property to children

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#56]
Often using an `obj` to group together widgets with similar properties.

It seems like `state` property for `obj` is not propagated down to the children. I'd like to change the `disabled` state for all the children at runtime (eg. disable widget interaction while not connected to HA).

**Comment by clydebarrow** [comment]
You could just pause LVGL, then no input events will be processed. Or hide the parent of any parts you want to disable.

LVGL 9 has a tree_walk function, not implemented in V8.
