### ISSUE TITLE
Internal fonts issue

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#59]
`config/_02_host_lvgl_5_demos.yaml:3627:52: error: ‘montserrat_8’ was not declared in this scope`

`config/_02_host_lvgl_5_demos.yaml:3627:53: error: ‘montserrat_10’ was not declared in this scope`

`config/_02_host_lvgl_5_demos.yaml:3635:53: error: ‘simsun_16_cjk’ was not declared in this scope`

https://github.com/clydebarrow/esphome/blob/1d5f949645aeaf4ada112e21dfcbee3057d78197/esphome/components/lvgl/defines.py#L37-L42

should probably be:

```
LV_FONTS = list(map(lambda size: f"montserrat_{size}", range(8, 50, 2))) + [
    "dejavu_16_persian_hebrew",
    "simsun_16_cjk",
    "unscii_8",
    "unscii_16",
]
```

**Comment by nielsnl68** [comment]
Currently i get the following issue as well:

```
src/esphome/components/font/font.h:53:8: error: 'void esphome::font::Font::print(int, int, esphome::display::Display*, esphome::Color, const char*, esphome::Color)' marked 'override', but does not override
   void print(int x_start, int y_start, display::Display *display, Color color, const char *text,
        ^~~~~
```
