### ISSUE TITLE
LVGL sensors

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#67]
OpenHASP has in the status information a detail about the memory LVGL uses:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/3a1e294a-3640-4113-b2d6-adce0608fdde)

This LVGL memory (`LV_MEM_SIZE`) afaik is something dedicated to it, and parts of it can be free.
Maybe it could be useful to have such diagnostic sensors configurable in ESPHome too, like the size of the configured LVGL memory and how much is free out of it, and fragmentation. 
A text sensor with the used LVGL version. 
A sensor with framerate peaks.

**Comment by clydebarrow** [comment]
Not applicable - the ESPHome LVGL implementation just uses the ESP heap, which is already available via the `debug` component. https://arc.net/l/quote/olalwsgc
